### ISSUE TITLE
文档中给的网盘地址被百度封了

### ISSUE THREAD

**Issue by lmcl90** [snakerflow-starter/snakerflow-spring-boot-starter#2]
源码部署那一节给的网盘地址：http://pan.baidu.com/s/1hqza8BU 打卡以后的提示是：

> 此链接分享内容可能因为涉及侵权、色情、反动、低俗等信息，无法访问！

**Comment by lmcl90** [comment]
http://snakerflow.cn:8081/book/install/README.html

**Comment by bigfish1129** [comment]
https://github.com/snakerflow-starter/snaker-web
可以从这里下载启动
